In [2]:
!pip3 install yfinance pandas ta-lib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (0.2.54)
Requirement already satisfied: pandas in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (2.2.3)
Requirement already satisfied: ta-lib in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (0.6.3)
Requirement already satisfied: numpy>=1.16.5 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (2.0.2)
Requirement already satisfied: pytz>=2022.5 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (2024.2)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (3.10.0)
Requirement already satisfied: multitasking>=0.0.7 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (4.13.3)
Requirement already satisfied: peewee>=3.16.2 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (3.17.9)
Requirement already satisfied: frozendict>=2.3.4 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.2)
Requirement already satisfied: soupsieve>1.2 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.7.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->yfinance) (2024.8.30)
Requirement already satisfied: idna<4,>=2.5 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/akashsetti/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->yfinance) (3.4.1)
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.

In [3]:
import pandas as pd
import numpy as np
import yfinance as yf

/Users/akashsetti/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [21]:
# tickers = ["^GSPC", "^GDAXI", "^IXIC", "^RUT", "^N225", "^FTSE"]
# start_date = "2010-01-01"
# end_date = "2024-12-31"

# data = {}

# for ticker in tickers:
#     data[ticker] = yf.download(ticker, start=start_date, end=end_date)


import numpy as np
import yfinance as yf
import talib
import pandas as pd

tickers = ["^GSPC", "^GDAXI", "^IXIC", "^RUT", "^N225", "^FTSE"]
start_date = "2010-01-01"
end_date = datetime.today().date()

data = {}

for ticker in tickers:
    df = yf.download(ticker, start=start_date, end=end_date)
    if df.empty:
        print(f"No data for {ticker}. Skipping.")
        continue

    # Explicitly convert columns to 1D numpy arrays of type float
    high = np.asarray(df['High'], dtype=float).ravel()
    low = np.asarray(df['Low'], dtype=float).ravel()
    close = np.asarray(df['Close'], dtype=float).ravel()
    volume = np.asarray(df['Volume'], dtype=float).ravel()

    # Optionally, check the shapes
    # print(f"{ticker} shapes -> High: {high.shape}, Low: {low.shape}, Close: {close.shape}")

    # Calculate technical indicators using these arrays
    try:
        df['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
    except Exception as e:
        print(f"Error computing AROONOSC for {ticker}: {e}")
    
    try:
        df['RSI'] = talib.RSI(close, timeperiod=14)
    except Exception as e:
        print(f"Error computing RSI for {ticker}: {e}")

    try:
        df['CCI'] = talib.CCI(high, low, close, timeperiod=14)
    except Exception as e:
        print(f"Error computing CCI for {ticker}: {e}")

    try:
        df['CMO'] = talib.CMO(close, timeperiod=14)
    except Exception as e:
        print(f"Error computing CMO for {ticker}: {e}")

    try:
        df['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
    except Exception as e:
        print(f"Error computing MFI for {ticker}: {e}")

    try:
        df['Williams_%R'] = talib.WILLR(high, low, close, timeperiod=14)
    except Exception as e:
        print(f"Error computing Williams %R for {ticker}: {e}")

    try:
        fastk, fastd = talib.STOCHF(high, low, close, fastk_period=14, fastd_period=3, fastd_matype=0)
        df['STOCHF_fastk'] = fastk
        df['STOCHF_fastd'] = fastd
    except Exception as e:
        print(f"Error computing STOCHF for {ticker}: {e}")
    
    data[ticker] = df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [13]:
# Combine data into one DataFrame with a multi-index for columns
df = pd.concat(data.values(), axis=1, keys=data.keys())
df

                  ^GSPC                                                       \
Price             Close         High          Low         Open        Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC         ^GSPC
Date
2010-01-04  1132.989990  1133.869995  1116.560059  1116.560059  3.991400e+09
2010-01-05  1136.520020  1136.630005  1129.660034  1132.660034  2.491020e+09
2010-01-06  1137.140015  1139.189941  1133.949951  1135.709961  4.972660e+09
2010-01-07  1141.689941  1142.459961  1131.319946  1136.270020  5.270680e+09
2010-01-08  1144.979980  1145.390015  1136.219971  1140.520020  4.389590e+09
...                 ...          ...          ...          ...           ...
2025-03-13  5521.520020  5597.779785  5504.649902  5594.450195  5.018980e+09
2025-03-14  5638.939941  5645.270020  5563.850098  5563.850098  4.863180e+09
2025-03-17  5675.120117  5703.520020  5631.120117  5635.600098  5.031770e+09
2025-03-18  5614.660156  5654.529785  5597.759766  5654.529785  4.666270e+09
2025-03-19  5675.290039  5715.330078  5622.200195  5632.370117  4.660090e+09

                                                                     ...  \
Price         AROONOSC        RSI         CCI        CMO        MFI  ...
Ticker                                                               ...
Date                                                                 ...
2010-01-04         NaN        NaN         NaN        NaN        NaN  ...
2010-01-05         NaN        NaN         NaN        NaN        NaN  ...
2010-01-06         NaN        NaN         NaN        NaN        NaN  ...
2010-01-07         NaN        NaN         NaN        NaN        NaN  ...
2010-01-08         NaN        NaN         NaN        NaN        NaN  ...
...                ...        ...         ...        ...        ...  ...
2025-03-13 -100.000000  27.860120 -128.441179 -44.279761  28.339016  ...
2025-03-14  -92.857143  37.672845  -77.321077 -24.654311  34.631494  ...
2025-03-17  -78.571429  40.364578  -41.022969 -19.270844  41.350501  ...
2025-03-18  -78.571429  37.453654  -57.747516 -25.092691  35.007103  ...
2025-03-19  -71.428571  41.972889  -20.792795 -16.054222  41.341448  ...

                  ^FTSE                                                  \
Price              Open        Volume   AROONOSC        RSI         CCI
Ticker            ^FTSE         ^FTSE
Date
2010-01-04  5412.899902  7.509420e+08        NaN        NaN         NaN
2010-01-05  5500.299805  1.149301e+09        NaN        NaN         NaN
2010-01-06  5522.500000  9.982953e+08        NaN        NaN         NaN
2010-01-07  5530.000000  1.162934e+09        NaN        NaN         NaN
2010-01-08  5526.700195  1.006421e+09        NaN        NaN         NaN
...                 ...           ...        ...        ...         ...
2025-03-13  8541.000000  7.727094e+08 -42.857143  40.946162 -114.731585
2025-03-14  8542.599609  7.702905e+08 -42.857143  48.987971  -61.125010
2025-03-17  8632.299805  8.456125e+08 -42.857143  52.699905  -13.372846
2025-03-18  8680.299805  1.112955e+09 -42.857143  54.547615   18.314589
2025-03-19  8705.200195  8.243836e+08 -42.857143  54.662509   14.539808


Price             CMO        MFI Williams_%R STOCHF_fastk STOCHF_fastd
Ticker
Date
2010-01-04        NaN        NaN         NaN          NaN          NaN
2010-01-05        NaN        NaN         NaN          NaN          NaN
2010-01-06        NaN        NaN         NaN          NaN          NaN
2010-01-07        NaN        NaN         NaN          NaN          NaN
2010-01-08        NaN        NaN         NaN          NaN          NaN
...               ...        ...         ...          ...          ...
2025-03-13 -18.107676  52.105186  -85.620769    14.379231    10.622767
2025-03-14  -2.024058  56.968457  -64.648088    35.351912    21.245457
2025-03-17   5.399809  56.769933  -53.425274    46.574726    32.101956
2025-03-18   9.095230  57.116975  -47.603347    52.396653    44.774430
2025-03-19   9.325019  50.897645  -47.252634    52.747366    50.572915

[3958 rows x 78 columns]

In [7]:
combined_data

                  ^GSPC                                                       \
Price             Close         High          Low         Open        Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC         ^GSPC
Date
2010-01-04  1132.989990  1133.869995  1116.560059  1116.560059  3.991400e+09
2010-01-05  1136.520020  1136.630005  1129.660034  1132.660034  2.491020e+09
2010-01-06  1137.140015  1139.189941  1133.949951  1135.709961  4.972660e+09
2010-01-07  1141.689941  1142.459961  1131.319946  1136.270020  5.270680e+09
2010-01-08  1144.979980  1145.390015  1136.219971  1140.520020  4.389590e+09
...                 ...          ...          ...          ...           ...
2025-03-13  5521.520020  5597.779785  5504.649902  5594.450195  5.018980e+09
2025-03-14  5638.939941  5645.270020  5563.850098  5563.850098  4.863180e+09
2025-03-17  5675.120117  5703.520020  5631.120117  5635.600098  5.031770e+09
2025-03-18  5614.660156  5654.529785  5597.759766  5654.529785  4.666270e+09
2025-03-19  5675.290039  5715.330078  5622.200195  5632.370117  4.660090e+09

                                                                     ...  \
Price         AROONOSC        RSI         CCI        CMO        MFI  ...
Ticker                                                               ...
Date                                                                 ...
2010-01-04         NaN        NaN         NaN        NaN        NaN  ...
2010-01-05         NaN        NaN         NaN        NaN        NaN  ...
2010-01-06         NaN        NaN         NaN        NaN        NaN  ...
2010-01-07         NaN        NaN         NaN        NaN        NaN  ...
2010-01-08         NaN        NaN         NaN        NaN        NaN  ...
...                ...        ...         ...        ...        ...  ...
2025-03-13 -100.000000  27.860120 -128.441179 -44.279761  28.339016  ...
2025-03-14  -92.857143  37.672845  -77.321077 -24.654311  34.631494  ...
2025-03-17  -78.571429  40.364578  -41.022969 -19.270844  41.350501  ...
2025-03-18  -78.571429  37.453654  -57.747516 -25.092691  35.007103  ...
2025-03-19  -71.428571  41.972889  -20.792795 -16.054222  41.341448  ...

                  ^FTSE                                                  \
Price              Open        Volume   AROONOSC        RSI         CCI
Ticker            ^FTSE         ^FTSE
Date
2010-01-04  5412.899902  7.509420e+08        NaN        NaN         NaN
2010-01-05  5500.299805  1.149301e+09        NaN        NaN         NaN
2010-01-06  5522.500000  9.982953e+08        NaN        NaN         NaN
2010-01-07  5530.000000  1.162934e+09        NaN        NaN         NaN
2010-01-08  5526.700195  1.006421e+09        NaN        NaN         NaN
...                 ...           ...        ...        ...         ...
2025-03-13  8541.000000  7.727094e+08 -42.857143  40.946162 -114.731585
2025-03-14  8542.599609  7.702905e+08 -42.857143  48.987971  -61.125010
2025-03-17  8632.299805  8.456125e+08 -42.857143  52.699905  -13.372846
2025-03-18  8680.299805  1.112955e+09 -42.857143  54.547615   18.314589
2025-03-19  8705.200195  8.243836e+08 -42.857143  54.662509   14.539808


Price             CMO        MFI Williams_%R STOCHF_fastk STOCHF_fastd
Ticker
Date
2010-01-04        NaN        NaN         NaN          NaN          NaN
2010-01-05        NaN        NaN         NaN          NaN          NaN
2010-01-06        NaN        NaN         NaN          NaN          NaN
2010-01-07        NaN        NaN         NaN          NaN          NaN
2010-01-08        NaN        NaN         NaN          NaN          NaN
...               ...        ...         ...          ...          ...
2025-03-13 -18.107676  52.105186  -85.620769    14.379231    10.622767
2025-03-14  -2.024058  56.968457  -64.648088    35.351912    21.245457
2025-03-17   5.399809  56.769933  -53.425274    46.574726    32.101956
2025-03-18   9.095230  57.116975  -47.603347    52.396653    44.774430
2025-03-19   9.325019  50.897645  -47.252634    52.747366    50.572915

[3958 rows x 78 columns]

In [ ]:
# combined_data.to_pickle('RLdata.pkl')

In [14]:
# print(combined_data.shape[1])


# Define the column names that correspond to OHLC data
ohlc_labels = ['Close', 'High', 'Low', 'Open', 'Volume']

# Assume 'df' is your unified DataFrame

# For a DataFrame with multi-indexed columns, the level that contains "Price", "Close", etc., is typically level 1.
df_ohlc = df.loc[:, df.columns.get_level_values(1).isin(ohlc_labels)]
df_indicators = df.loc[:, ~df.columns.get_level_values(1).isin(ohlc_labels)]

In [15]:
ohlc_keywords = ['Close', 'High', 'Low', 'Open', 'Volume']
ohlc_cols = [col for col in df.columns if any(keyword in col for keyword in ohlc_keywords)]
indicator_cols = [col for col in df.columns if col not in ohlc_cols]

df_ohlc = df[ohlc_cols]
df_indicators = df[indicator_cols]

In [16]:
df_ohlc

                  ^GSPC                                                       \
Price             Close         High          Low         Open        Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC         ^GSPC
Date
2010-01-04  1132.989990  1133.869995  1116.560059  1116.560059  3.991400e+09
2010-01-05  1136.520020  1136.630005  1129.660034  1132.660034  2.491020e+09
2010-01-06  1137.140015  1139.189941  1133.949951  1135.709961  4.972660e+09
2010-01-07  1141.689941  1142.459961  1131.319946  1136.270020  5.270680e+09
2010-01-08  1144.979980  1145.390015  1136.219971  1140.520020  4.389590e+09
...                 ...          ...          ...          ...           ...
2025-03-13  5521.520020  5597.779785  5504.649902  5594.450195  5.018980e+09
2025-03-14  5638.939941  5645.270020  5563.850098  5563.850098  4.863180e+09
2025-03-17  5675.120117  5703.520020  5631.120117  5635.600098  5.031770e+09
2025-03-18  5614.660156  5654.529785  5597.759766  5654.529785  4.666270e+09
2025-03-19  5675.290039  5715.330078  5622.200195  5632.370117  4.660090e+09

                  ^GDAXI                                            \
Price              Close          High           Low          Open
Ticker            ^GDAXI        ^GDAXI        ^GDAXI        ^GDAXI
Date
2010-01-04   6048.299805   6048.299805   5974.430176   5975.520020
2010-01-05   6031.859863   6058.020020   6015.669922   6043.939941
2010-01-06   6034.330078   6047.569824   5997.089844   6032.390137
2010-01-07   6019.359863   6037.569824   5961.250000   6016.799805
2010-01-08   6037.609863   6053.040039   5972.240234   6028.620117
...                  ...           ...           ...           ...
2025-03-13  22567.140625  22752.830078  22417.519531  22578.099609
2025-03-14  22986.820312  23049.480469  22465.119141  22501.339844
2025-03-17  23154.570312  23154.570312  22933.570312  22998.529297
2025-03-18  23380.699219  23476.009766  23240.560547  23266.650391
2025-03-19  23288.060547  23372.080078  23136.539062  23272.150391

                         ...         ^N225                              \
Price            Volume  ...         Close          High           Low
Ticker           ^GDAXI  ...         ^N225         ^N225         ^N225
Date                     ...
2010-01-04  104344400.0  ...  10654.790039  10694.490234  10608.139648
2010-01-05  117572100.0  ...  10681.830078  10791.040039  10655.570312
2010-01-06  108742400.0  ...  10731.450195  10768.610352  10661.169922
2010-01-07  133704300.0  ...  10681.660156  10774.000000  10636.669922
2010-01-08  126099000.0  ...  10798.320312  10816.450195  10677.559570
...                 ...  ...           ...           ...           ...
2025-03-13   78955600.0  ...  36790.031250  37326.269531  36776.941406
2025-03-14   93287400.0  ...  37053.101562  37154.390625  36594.039062
2025-03-17   67152000.0  ...  37396.519531  37563.269531  37377.550781
2025-03-18   80663300.0  ...  37845.421875  38004.199219  37822.871094
2025-03-19   79641400.0  ...  37751.878906  38128.578125  37751.878906

                                             ^FTSE                            \
Price               Open       Volume        Close         High          Low
Ticker             ^N225        ^N225        ^FTSE        ^FTSE        ^FTSE
Date
2010-01-04  10609.339844  104400000.0  5500.299805  5500.299805  5410.799805
2010-01-05  10719.440430  166200000.0  5522.500000  5536.399902  5480.700195
2010-01-06  10709.549805  181800000.0  5530.000000  5536.500000  5497.700195
2010-01-07  10742.750000  182600000.0  5526.700195  5551.700195  5499.799805
2010-01-08  10743.299805  211800000.0  5534.200195  5549.299805  5494.799805
...                  ...          ...          ...          ...          ...
2025-03-13  37081.640625  119300000.0  8542.599609  8581.599609  8513.700195
2025-03-14  36606.781250  134800000.0  8632.299805  8642.799805  8538.099609
2025-03-17  37453.828125  120300000.0  8680.299805  8688.400391  8625.000000
2025-03-18  37868.570312  133500000.0  8705.200195  8727.000000  8680.299805
2025-03-19  37839.390625  116800000.0  8706.700195  8718.700195  8662.599609


Price              Open        Volume
Ticker            ^FTSE         ^FTSE
Date
2010-01-04  5412.899902  7.509420e+08
2010-01-05  5500.299805  1.149301e+09
2010-01-06  5522.500000  9.982953e+08
2010-01-07  5530.000000  1.162934e+09
2010-01-08  5526.700195  1.006421e+09
...                 ...           ...
2025-03-13  8541.000000  7.727094e+08
2025-03-14  8542.599609  7.702905e+08
2025-03-17  8632.299805  8.456125e+08
2025-03-18  8680.299805  1.112955e+09
2025-03-19  8705.200195  8.243836e+08

[3958 rows x 30 columns]

In [1]:
# data = pd.read_hdf(f"data/data.h5", 'instruments')
df.to_hdf('tester.h5', key='^GSPC', mode='w')

NameError: name 'df' is not defined

In [5]:
data.head(100)

           ^RUT                       ^GDAXI                        ...  \
           Open High Low Close Volume   Open High Low Close Volume  ...
Date                                                                ...
1927-12-30  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-01-03  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-01-04  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-01-05  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-01-06  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
...         ...  ...  ..   ...    ...    ...  ...  ..   ...    ...  ...
1928-05-17  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-05-18  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-05-21  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-05-22  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...
1928-05-23  NaN  NaN NaN   NaN    NaN    NaN  NaN NaN   NaN    NaN  ...

                ^GSPC                                           CASH         \
                 Open       High        Low      Close Volume   Open   High
Date
1927-12-30  17.660000  17.660000  17.660000  17.660000    0.0  100.0  100.0
1928-01-03  17.760000  17.760000  17.760000  17.760000    0.0  100.0  100.0
1928-01-04  17.719999  17.719999  17.719999  17.719999    0.0  100.0  100.0
1928-01-05  17.549999  17.549999  17.549999  17.549999    0.0  100.0  100.0
1928-01-06  17.660000  17.660000  17.660000  17.660000    0.0  100.0  100.0
...               ...        ...        ...        ...    ...    ...    ...
1928-05-17  20.120001  20.120001  20.120001  20.120001    0.0  100.0  100.0
1928-05-18  19.920000  19.920000  19.920000  19.920000    0.0  100.0  100.0
1928-05-21  19.629999  19.629999  19.629999  19.629999    0.0  100.0  100.0
1928-05-22  19.360001  19.360001  19.360001  19.360001    0.0  100.0  100.0
1928-05-23  19.750000  19.750000  19.750000  19.750000    0.0  100.0  100.0


              Low  Close Volume
Date
1927-12-30  100.0  100.0  100.0
1928-01-03  100.0  100.0  100.0
1928-01-04  100.0  100.0  100.0
1928-01-05  100.0  100.0  100.0
1928-01-06  100.0  100.0  100.0
...           ...    ...    ...
1928-05-17  100.0  100.0  100.0
1928-05-18  100.0  100.0  100.0
1928-05-21  100.0  100.0  100.0
1928-05-22  100.0  100.0  100.0
1928-05-23  100.0  100.0  100.0

[100 rows x 35 columns]

In [ ]:
class PortfolioEnvironment(env):
    def __init__(self, data, lookback=14, config):
        self.data = data
        self.lookback = lookback
        self.config = config


        if config == 'MLP':
            # todo
        elif config == 'CNN':
            # todo
        else:
            raise ValueError('Invalid config')

In [18]:
tickers = ['CASH']

for ticker in tickers:
    df2= yf.download(ticker, start=start_date, end=end_date)

[*********************100%***********************]  1 of 1 completed

In [19]:
df2

Price           Close       High        Low       Open  Volume
Ticker           CASH       CASH       CASH       CASH    CASH
Date
2010-01-04   5.835885   6.380381   5.587370   6.380381   23100
2010-01-05   5.936406   6.028551   5.863806   5.880560    9300
2010-01-06   5.947575   6.140243   5.883352   5.933613   78000
2010-01-07   6.143036   6.143036   5.947576   6.003422   18000
2010-01-08   6.173749   6.173749   6.143034   6.145827    5700
...               ...        ...        ...        ...     ...
2025-03-13  69.940002  72.089996  69.889999  71.610001  150500
2025-03-14  71.900002  72.080002  70.190002  70.610001  156000
2025-03-17  72.040001  73.290001  71.449997  71.779999  134700
2025-03-18  72.309998  72.599998  71.290001  72.540001  142200
2025-03-19  73.669998  74.300003  72.339996  72.480003  198500

[3826 rows x 5 columns]

In [2]:
# from datetime import datetime

# today = datetime.today().date()
# print("Today's date is:", today)


import pandas as pd

In [18]:
example = pd.read_hdf('data/data.h5', 'instruments')

In [19]:
example

                   ^RUT                                                       \
                   Open         High          Low        Close        Volume
Date
1927-12-30          NaN          NaN          NaN          NaN           NaN
1928-01-03          NaN          NaN          NaN          NaN           NaN
1928-01-04          NaN          NaN          NaN          NaN           NaN
1928-01-05          NaN          NaN          NaN          NaN           NaN
1928-01-06          NaN          NaN          NaN          NaN           NaN
...                 ...          ...          ...          ...           ...
2024-05-02  1998.319946  2016.500000  1984.680054  2016.109985  4.381660e+09
2024-05-03  2044.219971  2054.850098  2030.819946  2035.719971  3.924990e+09
2024-05-06  2048.510010  2064.290039  2048.510010  2060.669922  3.683250e+09
2024-05-07  2062.159912  2077.810059  2062.159912  2064.649902  3.987890e+09
2024-05-08          NaN          NaN          NaN          NaN           NaN

                  ^GDAXI                                            \
                    Open          High           Low         Close
Date
1927-12-30           NaN           NaN           NaN           NaN
1928-01-03           NaN           NaN           NaN           NaN
1928-01-04           NaN           NaN           NaN           NaN
1928-01-05           NaN           NaN           NaN           NaN
1928-01-06           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-05-02  17935.779297  17981.039062  17875.980469  17896.500000
2024-05-03  17900.150391  18105.820312  17900.019531  18001.599609
2024-05-06  18001.130859  18199.150391  18001.130859  18175.210938
2024-05-07  18175.210938  18442.400391  18175.210938  18430.050781
2024-05-08  18430.250000  18542.099609  18428.380859  18531.949219

                        ...        ^GSPC                            \
                Volume  ...         Open         High          Low
Date                    ...
1927-12-30         NaN  ...    17.660000    17.660000    17.660000
1928-01-03         NaN  ...    17.760000    17.760000    17.760000
1928-01-04         NaN  ...    17.719999    17.719999    17.719999
1928-01-05         NaN  ...    17.549999    17.549999    17.549999
1928-01-06         NaN  ...    17.660000    17.660000    17.660000
...                ...  ...          ...          ...          ...
2024-05-02  71332200.0  ...  5049.319824  5073.209961  5011.049805
2024-05-03  71259900.0  ...  5122.779785  5139.120117  5101.220215
2024-05-06  46036600.0  ...  5142.419922  5181.000000  5142.419922
2024-05-07  85365200.0  ...  5187.200195  5200.229980  5178.959961
2024-05-08         0.0  ...          NaN          NaN          NaN

                                        CASH
                  Close        Volume   Open   High    Low  Close Volume
Date
1927-12-30    17.660000  0.000000e+00  100.0  100.0  100.0  100.0  100.0
1928-01-03    17.760000  0.000000e+00  100.0  100.0  100.0  100.0  100.0
1928-01-04    17.719999  0.000000e+00  100.0  100.0  100.0  100.0  100.0
1928-01-05    17.549999  0.000000e+00  100.0  100.0  100.0  100.0  100.0
1928-01-06    17.660000  0.000000e+00  100.0  100.0  100.0  100.0  100.0
...                 ...           ...    ...    ...    ...    ...    ...
2024-05-02  5064.200195  4.381660e+09  100.0  100.0  100.0  100.0  100.0
2024-05-03  5127.790039  3.924990e+09  100.0  100.0  100.0  100.0  100.0
2024-05-06  5180.740234  3.683250e+09  100.0  100.0  100.0  100.0  100.0
2024-05-07  5187.700195  3.987890e+09  100.0  100.0  100.0  100.0  100.0
2024-05-08          NaN           NaN  100.0  100.0  100.0  100.0  100.0

[24699 rows x 35 columns]

In [20]:
jfiefjc = example.loc["2000-01-01":].dropna()

In [21]:
jfiefjc

                   ^RUT                                                       \
                   Open         High          Low        Close        Volume
Date
2000-01-04   497.049988   497.049988   478.200012   478.380005  1.009000e+09
2000-01-05   478.380005   479.480011   467.559998   478.829987  1.085500e+09
2000-01-06   478.829987   480.190002   474.399994   475.339996  1.092300e+09
2000-01-07   475.339996   488.309998   475.339996   488.309998  1.225200e+09
2000-01-11   501.890015   501.910004   492.559998   492.609985  1.014000e+09
...                 ...          ...          ...          ...           ...
2024-04-25  1980.530029  1984.489990  1957.819946  1981.119995  3.958050e+09
2024-04-26  1984.530029  2005.010010  1984.420044  2002.000000  3.604140e+09
2024-04-30  2001.709961  2003.410034  1973.849976  1973.910034  4.082470e+09
2024-05-02  1998.319946  2016.500000  1984.680054  2016.109985  4.381660e+09
2024-05-07  2062.159912  2077.810059  2062.159912  2064.649902  3.987890e+09

                  ^GDAXI                                            \
                    Open          High           Low         Close
Date
2000-01-04   6747.240234   6755.359863   6510.459961   6586.950195
2000-01-05   6585.850098   6585.850098   6388.910156   6502.069824
2000-01-06   6501.450195   6539.310059   6402.629883   6474.919922
2000-01-07   6489.939941   6791.529785   6470.140137   6780.959961
2000-01-11   6926.040039   6943.830078   6821.259766   6891.250000
...                  ...           ...           ...           ...
2024-04-25  18088.169922  18100.750000  17795.960938  17917.279297
2024-04-26  17920.730469  18199.710938  17920.730469  18161.009766
2024-04-30  18119.929688  18153.689453  17920.720703  17932.169922
2024-05-02  17935.779297  17981.039062  17875.980469  17896.500000
2024-05-07  18175.210938  18442.400391  18175.210938  18430.050781

                         ...        ^GSPC                            \
                 Volume  ...         Open         High          Low
Date                     ...
2000-01-04   46678400.0  ...  1455.219971  1455.219971  1397.430054
2000-01-05   52682800.0  ...  1399.420044  1413.270020  1377.680054
2000-01-06   41180600.0  ...  1402.109985  1411.900024  1392.099976
2000-01-07   56058900.0  ...  1403.449951  1441.469971  1400.729980
2000-01-11   43890000.0  ...  1457.599976  1458.660034  1434.420044
...                 ...  ...          ...          ...          ...
2024-04-25  101517300.0  ...  5019.879883  5057.750000  4990.580078
2024-04-26   76008600.0  ...  5084.649902  5114.620117  5073.140137
2024-04-30   88206200.0  ...  5103.779785  5110.830078  5035.310059
2024-05-02   71332200.0  ...  5049.319824  5073.209961  5011.049805
2024-05-07   85365200.0  ...  5187.200195  5200.229980  5178.959961

                                        CASH
                  Close        Volume   Open   High    Low  Close Volume
Date
2000-01-04  1399.420044  1.009000e+09  100.0  100.0  100.0  100.0  100.0
2000-01-05  1402.109985  1.085500e+09  100.0  100.0  100.0  100.0  100.0
2000-01-06  1403.449951  1.092300e+09  100.0  100.0  100.0  100.0  100.0
2000-01-07  1441.469971  1.225200e+09  100.0  100.0  100.0  100.0  100.0
2000-01-11  1438.560059  1.014000e+09  100.0  100.0  100.0  100.0  100.0
...                 ...           ...    ...    ...    ...    ...    ...
2024-04-25  5048.419922  3.958050e+09  100.0  100.0  100.0  100.0  100.0
2024-04-26  5099.959961  3.604140e+09  100.0  100.0  100.0  100.0  100.0
2024-04-30  5035.689941  4.082470e+09  100.0  100.0  100.0  100.0  100.0
2024-05-02  5064.200195  4.381660e+09  100.0  100.0  100.0  100.0  100.0
2024-05-07  5187.700195  3.987890e+09  100.0  100.0  100.0  100.0  100.0

[5627 rows x 35 columns]

In [1]:
import pandas as pd

In [2]:
df_ex = pd.read_hdf('data/data.h5', key='instruments')
df_ex = df_ex.loc["2010-01-01":].dropna()

In [3]:
df_ex

                   ^RUT                                                       \
                   Open         High          Low        Close        Volume
Date
2010-01-04   628.109985   640.099976   628.109985   640.099976  3.991400e+09
2010-01-05   639.690002   641.890015   635.950012   638.489990  2.491020e+09
2010-01-06   638.289978   641.260010   636.400024   637.950012  4.972660e+09
2010-01-07   638.109985   642.070007   632.739990   641.969971  5.270680e+09
2010-01-08   640.340027   644.690002   639.559998   644.559998  4.389590e+09
...                 ...          ...          ...          ...           ...
2024-04-25  1980.530029  1984.489990  1957.819946  1981.119995  3.958050e+09
2024-04-26  1984.530029  2005.010010  1984.420044  2002.000000  3.604140e+09
2024-04-30  2001.709961  2003.410034  1973.849976  1973.910034  4.082470e+09
2024-05-02  1998.319946  2016.500000  1984.680054  2016.109985  4.381660e+09
2024-05-07  2062.159912  2077.810059  2062.159912  2064.649902  3.987890e+09

                  ^GDAXI                                            \
                    Open          High           Low         Close
Date
2010-01-04   5975.520020   6048.299805   5974.430176   6048.299805
2010-01-05   6043.939941   6058.020020   6015.669922   6031.859863
2010-01-06   6032.390137   6047.569824   5997.089844   6034.330078
2010-01-07   6016.799805   6037.569824   5961.250000   6019.359863
2010-01-08   6028.620117   6053.040039   5972.240234   6037.609863
...                  ...           ...           ...           ...
2024-04-25  18088.169922  18100.750000  17795.960938  17917.279297
2024-04-26  17920.730469  18199.710938  17920.730469  18161.009766
2024-04-30  18119.929688  18153.689453  17920.720703  17932.169922
2024-05-02  17935.779297  17981.039062  17875.980469  17896.500000
2024-05-07  18175.210938  18442.400391  18175.210938  18430.050781

                         ...        ^GSPC                            \
                 Volume  ...         Open         High          Low
Date                     ...
2010-01-04  104344400.0  ...  1116.560059  1133.869995  1116.560059
2010-01-05  117572100.0  ...  1132.660034  1136.630005  1129.660034
2010-01-06  108742400.0  ...  1135.709961  1139.189941  1133.949951
2010-01-07  133704300.0  ...  1136.270020  1142.459961  1131.319946
2010-01-08  126099000.0  ...  1140.520020  1145.390015  1136.219971
...                 ...  ...          ...          ...          ...
2024-04-25  101517300.0  ...  5019.879883  5057.750000  4990.580078
2024-04-26   76008600.0  ...  5084.649902  5114.620117  5073.140137
2024-04-30   88206200.0  ...  5103.779785  5110.830078  5035.310059
2024-05-02   71332200.0  ...  5049.319824  5073.209961  5011.049805
2024-05-07   85365200.0  ...  5187.200195  5200.229980  5178.959961

                                        CASH
                  Close        Volume   Open   High    Low  Close Volume
Date
2010-01-04  1132.989990  3.991400e+09  100.0  100.0  100.0  100.0  100.0
2010-01-05  1136.520020  2.491020e+09  100.0  100.0  100.0  100.0  100.0
2010-01-06  1137.140015  4.972660e+09  100.0  100.0  100.0  100.0  100.0
2010-01-07  1141.689941  5.270680e+09  100.0  100.0  100.0  100.0  100.0
2010-01-08  1144.979980  4.389590e+09  100.0  100.0  100.0  100.0  100.0
...                 ...           ...    ...    ...    ...    ...    ...
2024-04-25  5048.419922  3.958050e+09  100.0  100.0  100.0  100.0  100.0
2024-04-26  5099.959961  3.604140e+09  100.0  100.0  100.0  100.0  100.0
2024-04-30  5035.689941  4.082470e+09  100.0  100.0  100.0  100.0  100.0
2024-05-02  5064.200195  4.381660e+09  100.0  100.0  100.0  100.0  100.0
2024-05-07  5187.700195  3.987890e+09  100.0  100.0  100.0  100.0  100.0

[3303 rows x 35 columns]